spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teste
    username: postgres
    password: senhasegura
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true